# Generated by Django 4.0.4 on 2022-06-05 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nunReviews',
            new_name='numReviews',
        ),
    ]
